version: '3'

services:

  payload:
    build:
      dockerfile: ./dockerfile.dev
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "npm install && npm run dev"

volumes:
  data:
  node_modules: