version: '3'

services:

  tonelist:
    build:
      dockerfile: .
    env_file:
      - .env
      - .env.development
      - .env.local
      - .env.development.local
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "npm install && npm run dev"
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules: