version: '3'

services:
  tonelist:
    image: node:18-alpine
    env_file:
      - .env
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "npm install && npm run dev"
    depends_on:
      - lavalink
    environment:
      - LAVA_HOST=lavalink
    ports:
      - "3000:3000"
      - "5173:5173"

  lavalink:
    image: fredboat/lavalink:latest
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
    logging:
      driver: none
    ports:
      - "2333:2333"

volumes:
  node_modules: