version: '3'

services:
  tonelist:
    image: node:18-alpine
    env_file:
      - .env
      - .env.local
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "npm install && npm run dev"
    depends_on:
      - lavalink
    ports:
      - "3000:3000"
    environment:
      - LAVA_HOST=lavalink

  lavalink:
    image: fredboat/lavalink:latest
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
    logging:
      driver: none

volumes:
  node_modules: