version: '3'

services:
  tonelist:
    build:
      dockerfile: ./dockerfile
    env_file:
      - .env
      - .env.production
      - .env.local
      - .env.production.local
    working_dir: /home/node/app/
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data: