version: '3'

services:

  tonelist:
    image: node:18-alpine
    env_file:
      - .env
      - .env.development
      - .env.local
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "npm install && npm run dev"
    depends_on:
      - lavalink
    environment:
      NODE_ENV: development
      LAVA_HOST: lavalink
  
  lavalink:
    image: fredboat/lavalink:latest
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
    ports:
      - "2333:2333"
    logging:
      driver: none

volumes:
  data:
  node_modules: